### ISSUE TITLE
Why i cannot open the agf.exe after i build the source code?

### ISSUE THREAD

**Issue by skstudying** [cyanff/anime.gf#7]
I build the source code in the git repo:
`>npm run build:win `

Then i double-click the "agf-1.0.0-setup.exe" in the "dist" file.
Fine, installed.

Then i cant open the app after my double-clicking the "agf" on my desktop...

Why...

**Comment by skstudying** [comment]
Whats wrong with my operation?

**Comment by skstudying** [comment]
Sry. I found the reason : my own electron-vite is v2.2.0 while this proj is v2.0.0  ... 
Please close this issue.

By the way. I **LOVE** this project and where can i donate!!!  @cyanff

**Comment by cyanff** [comment]
ahh i see.
ty for the offer! though I'm planning for the web & mobile app to be monetized so i'd feel bad accepting donations
super appreciate it though <3
