### ISSUE TITLE
[BUG] Support Ollama

### ISSUE THREAD

**Issue by wwjCMP** [cyanff/anime.gf#8]
Ollama is not compatible with the OPENAI API

**Comment by cyanff** [comment]
heyy, were you using the "custom openai compatible API" option?
i've only just pushed the changes a few days ago
will roll this out in the v0.0.2 release
![image](https://github.com/cyanff/anime.gf/assets/79063400/f6d2fe5c-b9a4-4916-b010-92c4f5381c4b)

**Comment by cyanff** [comment]
okk i've released it, let me know if there are any issues!
https://github.com/cyanff/anime.gf/releases/tag/0.0.2
