### ISSUE TITLE
Hope to add a third-party OpenAI API_URL interface

### ISSUE THREAD

**Issue by Zoumachuan** [cyanff/anime.gf#9]
In fact, for some reasons, I am unable to use the official apikey. If possible, I would like to manually add an option to set the OpenAI API_URL myself, which will bring me great convenience. Thank you very much to the developers!
![微信截图_20240508104758](https://github.com/cyanff/anime.gf/assets/123653723/dc754a25-ba7a-4a86-9e2d-b1f43d46eb10)

**Comment by cyanff** [comment]
heyy, just released support for this in v0.0.2!
https://github.com/cyanff/anime.gf/releases/tag/0.0.2
lmk if there are any issues :)

**Comment by Zoumachuan** [comment]
> heyy, just released support for this in v0.0.2! https://github.com/cyanff/anime.gf/releases/tag/0.0.2 lmk if there are any issues :)

Thanks!

**Comment by fengyunzaidushi** [comment]
Why is it that I have installed the 0.0.2 windows version, but I still don't see a place to set the base_url
![image](https://github.com/user-attachments/assets/d272d8f8-4186-48ef-b922-4c1a174965e3)
![image](https://github.com/user-attachments/assets/4fba4a3c-8438-4a37-9329-69415171ee0c)
